export {
  addLayer,
  addPath,
  addSwatch,
  applySwatch,
  createGradient,
  createId,
  createNewDocument,
  defaultDocumentHeight,
  defaultDocumentWidth,
  DUPLICATE_OFFSET,
  deleteAnchors,
  INSERT_POINT_MARGIN,
  insertPoint,
  deleteLayer,
  deleteObjects,
  deletableObjectIds,
  alignObjects,
  canAlignObjects,
  countAlignable,
  addEmptyPoint,
  isEmptyPoint,
  addShape,
  clampShapeCount,
  ELLIPSE_KAPPA,
  isShapeKind,
  shapeSource,
  shapeSourceFromDrag,
  SHAPE_NAMES,
  duplicateObjects,
  isInteractionLocked,
  layersFrontToBack,
  nextSeriesName,
  objectsInPaintOrder,
  objectsOnLayer,
  reorderLayer,
  anchorPointType,
  setAnchorHandle,
  setAnchorPointType,
  setAnchorPosition,
  setObjectStyle,
  sourceToPathData,
  svgStrokeDefaults,
  rotationOriginDocument,
  transformWithRotationOrigin,
  translateAnchors,
  updateLayer,
} from './model';
export type {
  AlignEdge,
  AlignTarget,
  Anchor,
  AnchorPointType,
  Document,
  DocumentSize,
  Layer,
  Gradient,
  GradientStop,
  GradientType,
  Modifier,
  ObjectTransform,
  Segment,
  ShapeDrag,
  ShapeKind,
  ShapeObjectResult,
  ShapePlacement,
  SourcePath,
  StrokeAlign,
  StrokeLinecap,
  StrokeLinejoin,
  Style,
  Subpath,
  Swatch,
  Vec2,
  VectorObject,
  ViewBox,
  ViewportCamera,
} from './model';
export { captureClipperHold, evaluateDocument, evaluateObject } from './eval/evaluate';
export type { ClipperHold, EvaluatedGeometry } from './eval/evaluate';
export { exportSvg, importSvg } from './io';
export type { SaveMode, SvgImportResult } from './io';
export { SessionService } from './session.service';
export type { SessionSlice } from './session.service';
